### ISSUE TITLE
Select word and line doesn't work on macos

### ISSUE THREAD

**Issue by darricheng** [sunaku/glove80-keymaps#3]
In v32, the select word macro selects the entire line, while the select line macro selects the current line and everything below.

I'm still very new to the layout and the whole ZMK customisation, so I could use some advice on how to edit and test the macro.

**Comment by sunaku** [comment]
Please check whether manually typing out [these ZMK macros' keystrokes](https://github.com/sunaku/glove80-keymaps/blob/main/keymap.dtsi#L591-L695) has the intended effect:

* select_word_right: &kp LG(RIGHT) &kp LG(LEFT) &kp LG(LS(RIGHT))
* select_word_left: &kp LG(LEFT) &kp LG(RIGHT) &kp LG(LS(LEFT))
* extend_word_right: &kp LG(LS(RIGHT))
* extend_word_left: &kp LG(LS(LEFT))
* select_line_right: &kp HOME &kp LS(END)
* select_line_left: &kp END &kp LS(HOME)
* extend_line_right: &kp LS(DOWN) &kp LS(END)
* extend_line_left: &kp LS(UP) &kp LS(HOME)

If those worked successfully, the problem may be timing: I think the macros might be emitting their synthetic keystrokes too rapidly for your system, so you can try increasing the `SELECT_WORD_DELAY` setting's value to slow down their emission rate:

```dts
#define SELECT_WORD_DELAY 40
```

**Comment by sunaku** [comment]
You are correct! ✅  Upon closer study of [this listing](https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts#Text_editing), I see that "Go to next word" on macOS is Opt+Right instead of Cmd+Right. 😅  I naively assumed that, like Ctrl in Windows and Linux, a single modifier was used for both word-wise and line-wise motion in macOS too: that was the purpose of the `_C` definition -- to abstract Ctrl vs Cmd as `_C` so that the same underlying ZMK macro logic could be reused across operating systems.

As for understanding the select_word macro, it's just a custom shifted pair (like `&parang` which is a parenthesis by default or an angle bracket when Shift is held down) that defaults to select_word_right and alternates to select_word_left if Shift is held down -- see "mod-morph" in ZMK docs for details.  Effectively, this lets us select a word by going rightward by default and, optionally, reverse direction by adding a Shift modifier to our select_word keystroke.

**Comment by darricheng** [comment]
Thanks for the explanation! I modified the files accordingly as per the linked PR and have tested it to work on my own mac.
